// Pure physics functions — no DOM, no React dependencies.
// Based on "The Physics of Filter Coffee" by Jonathan Gagné (2020).

/** Dynamic viscosity of water (Pa·s) — Andrade equation */
export function dynamicViscosity(T_celsius: number): number {
  return 2.414e-5 * Math.pow(10, 247.8 / (T_celsius + 273.15 - 140));
}

/** Water density (kg/m³) with thermal expansion */
export function waterDensity(T_celsius: number): number {
  return 1000 * (1 - (T_celsius - 4) * (T_celsius - 4) * 6e-6);
}

/** Kinematic viscosity ν = μ/ρ (m²/s) — controls flow speed in Darcy's Law */
export function kinematicViscosity(T_celsius: number): number {
  return dynamicViscosity(T_celsius) / waterDensity(T_celsius);
}

/**
 * Hydraulic permeability of coffee bed (m²) — Kozeny-Carman model.
 * k ∝ d² — doubling grind size quadruples permeability.
 * Shape factor calibrated so 600µm grind + standard V60 ≈ 3 min brew.
 */
export function permeability(grindMicrons: number): number {
  const d = grindMicrons * 1e-6;
  const porosity = 0.40;
  const shapeFactor = 0.045; // calibrated for realistic multi-pour V60 brew times (~3 min)
  return (shapeFactor * d * d * Math.pow(porosity, 3)) /
    (180 * Math.pow(1 - porosity, 2));
}

/**
 * Diffusion coefficient scaling factor relative to 93°C reference.
 * D = μ_p · k_B · T → D ∝ T/μ (Einstein-Smoluchowski).
 * Higher temp = faster extraction.
 */
export function diffusionFactor(T_celsius: number): number {
  const Tk = T_celsius + 273.15;
  const Tref = 93 + 273.15;
  return (Tk / Tref) * (dynamicViscosity(93) / dynamicViscosity(T_celsius));
}

/**
 * Surface area scaling with grind size.
 * Finer grind → inversely proportional more surface → faster dissolution (Noyes-Whitney).
 */
export function surfaceAreaFactor(grindMicrons: number): number {
  return 600 / grindMicrons;
}

/**
 * Roast-level cell accessibility factor — how much of the coffee's surface
 * is actually reachable by water at a given temperature.
 *
 * Light roasts retain their dense cell structure. The heavier aromatic and
 * sweetness compounds locked inside those cells have high molecular mass and
 * low mobility (μ_p in Einstein-Smoluchowski), requiring higher thermal energy
 * to diffuse out. Below ~90°C, extraction is significantly reduced.
 *
 * Dark roasts: heavily degraded cell walls make compounds readily accessible
 * even at low temperatures. However, above ~90°C the bitter melanoidins and
 * acrid pyrolytic degradation compounds become increasingly soluble — pushing
 * EY past the ideal 22% ceiling quickly and producing a harsh cup. The factor
 * rises steeply with temperature to model this over-extraction risk.
 *
 * Medium roast: baseline = 1.0 (flat — wide temperature tolerance).
 */
export function roastCellFactor(
  roastLevel: 'light' | 'medium' | 'dark',
  temp: number,
): number {
  const t = Math.max(70, Math.min(100, temp));
  if (roastLevel === 'medium') return 1.00;
  if (roastLevel === 'light') {
    // Dense cell structure; heavy compounds need high thermal energy
    // 0.60 at 70°C → 1.00 at 100°C
    return 0.60 + (t - 70) * (0.40 / 30);
  }
  // Dark: porous structure extracts readily, but bitter compounds
  // become increasingly soluble above 90°C → over-extraction at high temps.
  // 1.00 at 70°C → 1.20 at 100°C (steeper than light, already accessible)
  return 1.00 + (t - 70) * (0.20 / 30);
}

// ---- Agitation model ----

/**
 * Agitation energy generated by a pour hitting the coffee bed.
 * Higher pour rate = more kinetic energy = more turbulence.
 * Returns an energy increment per second of pouring.
 */
export function agitationFromPour(pourRate: number): number {
  // Normalize: 3 ml/s is a gentle pour, 10 ml/s is aggressive
  return Math.min(1.0, (pourRate / 3.0) * 0.25);
}

/**
 * Decay agitation energy over time.
 * Turbulence dissipates exponentially — half-life ~0.25s.
 */
export function decayAgitation(energy: number, dt: number): number {
  return energy * Math.exp(-3.0 * dt);
}

/**
 * How agitation affects permeability.
 * Turbulence disrupts the fines layer on top of the bed,
 * temporarily increasing effective permeability by up to 50%.
 */
export function agitationPermeabilityMultiplier(energy: number): number {
  return 1.0 + 0.5 * energy;
}

/**
 * Darcy velocity through the bed (m/s).
 * v = k·g·h / (ν·L) — the actual speed of water movement.
 */
export function darcyVelocity(
  k: number, g: number, h: number, nu: number, L: number
): number {
  if (h <= 0) return 0;
  return (k * g * h) / (nu * L);
}

/**
 * Darcy flow rate Q (m³/s).
 * Q = v · A = (k·A·g·h) / (ν·L)
 */
export function darcyFlowRate(
  k: number, A: number, g: number, h: number, nu: number, L: number,
  geoFactor: number
): number {
  if (h <= 0) return 0;
  return (k * A * g * h) / (nu * L) * geoFactor;
}

/** Coffee bed depth (mm) given dose, dripper area, and type */
export function bedDepthMM(
  dose: number, areaTopMM2: number, dripperType: 'cone' | 'cylinder'
): number {
  const bulkDensity = 0.00043; // g/mm³ (430 kg/m³)
  const effectiveAreaFactor = dripperType === 'cone' ? 0.45 : 1.0;
  return dose / (bulkDensity * areaTopMM2 * effectiveAreaFactor);
}

/**
 * V60 cone half-angle: 30° from the central axis (total opening angle = 60°,
 * which is the origin of the "V60" name).
 */
export const V60_HALF_ANGLE = Math.PI / 6; // 30°

/**
 * For a conical V60 dripper, compute the actual physical diameter at the top
 * of the coffee bed using true cone geometry.
 *
 * Volume of a cone up to height h from tip: V = π·h³·tan²(θ)/3
 * Solving for h given the bed volume: h = cbrt(3V / (π·tan²(θ)))
 *
 * Returns the bed top diameter in mm (capped at topDiameterMM).
 */
export function coneBedTopDiameterMM(dose: number, topDiameterMM: number): number {
  const bulkDensity = 0.00043; // g/mm³ (430 kg/m³)
  const V_bed = dose / bulkDensity; // mm³
  const t = Math.tan(V60_HALF_ANGLE); // tan(30°) ≈ 0.577
  const h_bed = Math.cbrt((3 * V_bed) / (Math.PI * t * t));
  return Math.min(2 * h_bed * t, topDiameterMM);
}

/**
 * For a conical dripper, compute the water surface diameter given
 * the actual bed height from the tip and the current water column height.
 * Both inputs in mm. Returns diameter in mm.
 */
export function coneWaterSurfaceDiameterMM(
  h_bed_from_tip_mm: number, wColMM: number, topDiameterMM: number
): number {
  const t = Math.tan(V60_HALF_ANGLE);
  return Math.min(2 * (h_bed_from_tip_mm + wColMM) * t, topDiameterMM);
}

/**
 * Fraction of flow that bypasses the coffee bed due to poor pouring technique.
 * Higher = more water reaches the cup without extracting, lowering EY and TDS.
 * Based on pour pattern, paper avoidance, and whether the bed is levelled by swirling.
 */
export function channelingFraction(
  pourPattern: 'center' | 'circular',
  avoidPaper: boolean,
  swirl: boolean
): number {
  // Lookup table from Gagné's technique analysis.
  // Previous formula used Math.max(0.03, …) which swallowed the swirl bonus
  // in the best-case scenario (circular + avoidPaper): both swirl=true and
  // swirl=false produced 0.03, making the checkbox have no visible effect.
  const key = `${pourPattern}-${avoidPaper}-${swirl}` as const;
  const table: Record<string, number> = {
    'circular-true-true':   0.03,
    'circular-true-false':  0.06,
    'circular-false-true':  0.10,
    'circular-false-false': 0.14,
    'center-true-true':     0.10,
    'center-true-false':    0.14,
    'center-false-true':    0.17,
    'center-false-false':   0.21,
  };
  return table[key] ?? 0.03;
}

/** Liquid retained ratio — water trapped in spent coffee bed */
export const LRR = 2.0;

/** Gravity (m/s²) */
export const G = 9.81;
